// flow-typed signature: e890d44d872d738b50f647da3fb3c1db
// flow-typed version: <<STUB>>/composable-middleware_v^0.3.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'composable-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'composable-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'composable-middleware/Gruntfile' {
  declare module.exports: any;
}

declare module 'composable-middleware/lib/composable-middleware' {
  declare module.exports: any;
}

declare module 'composable-middleware/lib/middleware-common-object' {
  declare module.exports: any;
}

// Filename aliases
declare module 'composable-middleware/Gruntfile.js' {
  declare module.exports: $Exports<'composable-middleware/Gruntfile'>;
}
declare module 'composable-middleware/index' {
  declare module.exports: $Exports<'composable-middleware'>;
}
declare module 'composable-middleware/index.js' {
  declare module.exports: $Exports<'composable-middleware'>;
}
declare module 'composable-middleware/lib/composable-middleware.js' {
  declare module.exports: $Exports<'composable-middleware/lib/composable-middleware'>;
}
declare module 'composable-middleware/lib/middleware-common-object.js' {
  declare module.exports: $Exports<'composable-middleware/lib/middleware-common-object'>;
}
