// flow-typed signature: 5563215ed1b6a930b67fcff208e8487f
// flow-typed version: <<STUB>>/cron_v^1.2.1/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cron/lib/cron' {
  declare module.exports: any;
}

declare module 'cron/test' {
  declare module.exports: any;
}

declare module 'cron/tests/test-cron' {
  declare module.exports: any;
}

declare module 'cron/tests/test-crontime' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cron/lib/cron.js' {
  declare module.exports: $Exports<'cron/lib/cron'>;
}
declare module 'cron/test.js' {
  declare module.exports: $Exports<'cron/test'>;
}
declare module 'cron/tests/test-cron.js' {
  declare module.exports: $Exports<'cron/tests/test-cron'>;
}
declare module 'cron/tests/test-crontime.js' {
  declare module.exports: $Exports<'cron/tests/test-crontime'>;
}
