// flow-typed signature: a1bf5b48a2623ee8544f1a8b4de473c4
// flow-typed version: <<STUB>>/eslint-config-fullstack_v^2.7.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-fullstack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-fullstack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-fullstack/react' {
  declare module.exports: any;
}

declare module 'eslint-config-fullstack/rules/base' {
  declare module.exports: any;
}

declare module 'eslint-config-fullstack/rules/react' {
  declare module.exports: any;
}

declare module 'eslint-config-fullstack/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-fullstack/index' {
  declare module.exports: $Exports<'eslint-config-fullstack'>;
}
declare module 'eslint-config-fullstack/index.js' {
  declare module.exports: $Exports<'eslint-config-fullstack'>;
}
declare module 'eslint-config-fullstack/react.js' {
  declare module.exports: $Exports<'eslint-config-fullstack/react'>;
}
declare module 'eslint-config-fullstack/rules/base.js' {
  declare module.exports: $Exports<'eslint-config-fullstack/rules/base'>;
}
declare module 'eslint-config-fullstack/rules/react.js' {
  declare module.exports: $Exports<'eslint-config-fullstack/rules/react'>;
}
declare module 'eslint-config-fullstack/test/test.js' {
  declare module.exports: $Exports<'eslint-config-fullstack/test/test'>;
}
