// flow-typed signature: 460834df63884bfdaa765585d92a873f
// flow-typed version: <<STUB>>/express-brute_v^1.0.1/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-brute'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-brute' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-brute/lib/AbstractClientStore' {
  declare module.exports: any;
}

declare module 'express-brute/lib/MemoryStore' {
  declare module.exports: any;
}

declare module 'express-brute/mock/ResponseMock' {
  declare module.exports: any;
}

declare module 'express-brute/spec/ExpessBrute' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-brute/index' {
  declare module.exports: $Exports<'express-brute'>;
}
declare module 'express-brute/index.js' {
  declare module.exports: $Exports<'express-brute'>;
}
declare module 'express-brute/lib/AbstractClientStore.js' {
  declare module.exports: $Exports<'express-brute/lib/AbstractClientStore'>;
}
declare module 'express-brute/lib/MemoryStore.js' {
  declare module.exports: $Exports<'express-brute/lib/MemoryStore'>;
}
declare module 'express-brute/mock/ResponseMock.js' {
  declare module.exports: $Exports<'express-brute/mock/ResponseMock'>;
}
declare module 'express-brute/spec/ExpessBrute.js' {
  declare module.exports: $Exports<'express-brute/spec/ExpessBrute'>;
}
