// flow-typed signature: ed9cff58f1e574f9a3305dcfe99c5f74
// flow-typed version: <<STUB>>/express-https-redirect_v^1.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-https-redirect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-https-redirect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-https-redirect/redirect' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-https-redirect/redirect.js' {
  declare module.exports: $Exports<'express-https-redirect/redirect'>;
}
