// flow-typed signature: f58ba64e2fcb67346145a66ad0f7588b
// flow-typed version: <<STUB>>/express-brute-sequelize_v0.0.7/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-brute-sequelize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-brute-sequelize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-brute-sequelize/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-brute-sequelize/index' {
  declare module.exports: $Exports<'express-brute-sequelize'>;
}
declare module 'express-brute-sequelize/index.js' {
  declare module.exports: $Exports<'express-brute-sequelize'>;
}
declare module 'express-brute-sequelize/test/test.js' {
  declare module.exports: $Exports<'express-brute-sequelize/test/test'>;
}
