// flow-typed signature: 78d5ddd6ad3b6242d30e701b71d79928
// flow-typed version: <<STUB>>/sinon-stub-promise_v^4.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sinon-stub-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sinon-stub-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sinon-stub-promise/spec/index_spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sinon-stub-promise/index' {
  declare module.exports: $Exports<'sinon-stub-promise'>;
}
declare module 'sinon-stub-promise/index.js' {
  declare module.exports: $Exports<'sinon-stub-promise'>;
}
declare module 'sinon-stub-promise/spec/index_spec.js' {
  declare module.exports: $Exports<'sinon-stub-promise/spec/index_spec'>;
}
