// flow-typed signature: 447d0bfd07631c4f6da55103c43fe930
// flow-typed version: <<STUB>>/twilio_v^2.11.1/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'twilio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'twilio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'twilio/config.sample' {
  declare module.exports: any;
}

declare module 'twilio/examples/example' {
  declare module.exports: any;
}

declare module 'twilio/lib/AccessToken' {
  declare module.exports: any;
}

declare module 'twilio/lib/Capability' {
  declare module.exports: any;
}

declare module 'twilio/lib/Client' {
  declare module.exports: any;
}

declare module 'twilio/lib/index' {
  declare module.exports: any;
}

declare module 'twilio/lib/IpMessagingClient' {
  declare module.exports: any;
}

declare module 'twilio/lib/LookupsClient' {
  declare module.exports: any;
}

declare module 'twilio/lib/MonitorClient' {
  declare module.exports: any;
}

declare module 'twilio/lib/PricingClient' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/Accounts' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/Addresses' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/AvailablePhoneNumbers' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/Calls' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/Conferences' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/generate' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/IncomingPhoneNumbers' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/ip_messaging/Credentials' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/ip_messaging/Services' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/ListInstanceResource' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/lookups/PhoneNumbers' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/Messages' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/monitor/Alerts' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/monitor/Events' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/NextGenListInstanceResource' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/NextGenListResource' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/pricing/Messaging' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/pricing/PhoneNumbers' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/pricing/Voice' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/Queues' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/Recordings' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/sip/CredentialLists' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/sip/Domains' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/sip/IpAccessControlLists' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/task_router/WorkflowBuilder' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/task_router/Workspaces' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/trunking/Trunks' {
  declare module.exports: any;
}

declare module 'twilio/lib/resources/UsageRecords' {
  declare module.exports: any;
}

declare module 'twilio/lib/RestClient' {
  declare module.exports: any;
}

declare module 'twilio/lib/TaskRouterCapability' {
  declare module.exports: any;
}

declare module 'twilio/lib/TaskRouterClient' {
  declare module.exports: any;
}

declare module 'twilio/lib/TaskRouterTaskQueueCapability' {
  declare module.exports: any;
}

declare module 'twilio/lib/TaskRouterWorkerCapability' {
  declare module.exports: any;
}

declare module 'twilio/lib/TaskRouterWorkspaceCapability' {
  declare module.exports: any;
}

declare module 'twilio/lib/TrunkingClient' {
  declare module.exports: any;
}

declare module 'twilio/lib/TwimlResponse' {
  declare module.exports: any;
}

declare module 'twilio/lib/utils' {
  declare module.exports: any;
}

declare module 'twilio/lib/webhooks' {
  declare module.exports: any;
}

// Filename aliases
declare module 'twilio/config.sample.js' {
  declare module.exports: $Exports<'twilio/config.sample'>;
}
declare module 'twilio/examples/example.js' {
  declare module.exports: $Exports<'twilio/examples/example'>;
}
declare module 'twilio/index' {
  declare module.exports: $Exports<'twilio'>;
}
declare module 'twilio/index.js' {
  declare module.exports: $Exports<'twilio'>;
}
declare module 'twilio/lib/AccessToken.js' {
  declare module.exports: $Exports<'twilio/lib/AccessToken'>;
}
declare module 'twilio/lib/Capability.js' {
  declare module.exports: $Exports<'twilio/lib/Capability'>;
}
declare module 'twilio/lib/Client.js' {
  declare module.exports: $Exports<'twilio/lib/Client'>;
}
declare module 'twilio/lib/index.js' {
  declare module.exports: $Exports<'twilio/lib/index'>;
}
declare module 'twilio/lib/IpMessagingClient.js' {
  declare module.exports: $Exports<'twilio/lib/IpMessagingClient'>;
}
declare module 'twilio/lib/LookupsClient.js' {
  declare module.exports: $Exports<'twilio/lib/LookupsClient'>;
}
declare module 'twilio/lib/MonitorClient.js' {
  declare module.exports: $Exports<'twilio/lib/MonitorClient'>;
}
declare module 'twilio/lib/PricingClient.js' {
  declare module.exports: $Exports<'twilio/lib/PricingClient'>;
}
declare module 'twilio/lib/resources/Accounts.js' {
  declare module.exports: $Exports<'twilio/lib/resources/Accounts'>;
}
declare module 'twilio/lib/resources/Addresses.js' {
  declare module.exports: $Exports<'twilio/lib/resources/Addresses'>;
}
declare module 'twilio/lib/resources/AvailablePhoneNumbers.js' {
  declare module.exports: $Exports<'twilio/lib/resources/AvailablePhoneNumbers'>;
}
declare module 'twilio/lib/resources/Calls.js' {
  declare module.exports: $Exports<'twilio/lib/resources/Calls'>;
}
declare module 'twilio/lib/resources/Conferences.js' {
  declare module.exports: $Exports<'twilio/lib/resources/Conferences'>;
}
declare module 'twilio/lib/resources/generate.js' {
  declare module.exports: $Exports<'twilio/lib/resources/generate'>;
}
declare module 'twilio/lib/resources/IncomingPhoneNumbers.js' {
  declare module.exports: $Exports<'twilio/lib/resources/IncomingPhoneNumbers'>;
}
declare module 'twilio/lib/resources/ip_messaging/Credentials.js' {
  declare module.exports: $Exports<'twilio/lib/resources/ip_messaging/Credentials'>;
}
declare module 'twilio/lib/resources/ip_messaging/Services.js' {
  declare module.exports: $Exports<'twilio/lib/resources/ip_messaging/Services'>;
}
declare module 'twilio/lib/resources/ListInstanceResource.js' {
  declare module.exports: $Exports<'twilio/lib/resources/ListInstanceResource'>;
}
declare module 'twilio/lib/resources/lookups/PhoneNumbers.js' {
  declare module.exports: $Exports<'twilio/lib/resources/lookups/PhoneNumbers'>;
}
declare module 'twilio/lib/resources/Messages.js' {
  declare module.exports: $Exports<'twilio/lib/resources/Messages'>;
}
declare module 'twilio/lib/resources/monitor/Alerts.js' {
  declare module.exports: $Exports<'twilio/lib/resources/monitor/Alerts'>;
}
declare module 'twilio/lib/resources/monitor/Events.js' {
  declare module.exports: $Exports<'twilio/lib/resources/monitor/Events'>;
}
declare module 'twilio/lib/resources/NextGenListInstanceResource.js' {
  declare module.exports: $Exports<'twilio/lib/resources/NextGenListInstanceResource'>;
}
declare module 'twilio/lib/resources/NextGenListResource.js' {
  declare module.exports: $Exports<'twilio/lib/resources/NextGenListResource'>;
}
declare module 'twilio/lib/resources/pricing/Messaging.js' {
  declare module.exports: $Exports<'twilio/lib/resources/pricing/Messaging'>;
}
declare module 'twilio/lib/resources/pricing/PhoneNumbers.js' {
  declare module.exports: $Exports<'twilio/lib/resources/pricing/PhoneNumbers'>;
}
declare module 'twilio/lib/resources/pricing/Voice.js' {
  declare module.exports: $Exports<'twilio/lib/resources/pricing/Voice'>;
}
declare module 'twilio/lib/resources/Queues.js' {
  declare module.exports: $Exports<'twilio/lib/resources/Queues'>;
}
declare module 'twilio/lib/resources/Recordings.js' {
  declare module.exports: $Exports<'twilio/lib/resources/Recordings'>;
}
declare module 'twilio/lib/resources/sip/CredentialLists.js' {
  declare module.exports: $Exports<'twilio/lib/resources/sip/CredentialLists'>;
}
declare module 'twilio/lib/resources/sip/Domains.js' {
  declare module.exports: $Exports<'twilio/lib/resources/sip/Domains'>;
}
declare module 'twilio/lib/resources/sip/IpAccessControlLists.js' {
  declare module.exports: $Exports<'twilio/lib/resources/sip/IpAccessControlLists'>;
}
declare module 'twilio/lib/resources/task_router/WorkflowBuilder.js' {
  declare module.exports: $Exports<'twilio/lib/resources/task_router/WorkflowBuilder'>;
}
declare module 'twilio/lib/resources/task_router/Workspaces.js' {
  declare module.exports: $Exports<'twilio/lib/resources/task_router/Workspaces'>;
}
declare module 'twilio/lib/resources/trunking/Trunks.js' {
  declare module.exports: $Exports<'twilio/lib/resources/trunking/Trunks'>;
}
declare module 'twilio/lib/resources/UsageRecords.js' {
  declare module.exports: $Exports<'twilio/lib/resources/UsageRecords'>;
}
declare module 'twilio/lib/RestClient.js' {
  declare module.exports: $Exports<'twilio/lib/RestClient'>;
}
declare module 'twilio/lib/TaskRouterCapability.js' {
  declare module.exports: $Exports<'twilio/lib/TaskRouterCapability'>;
}
declare module 'twilio/lib/TaskRouterClient.js' {
  declare module.exports: $Exports<'twilio/lib/TaskRouterClient'>;
}
declare module 'twilio/lib/TaskRouterTaskQueueCapability.js' {
  declare module.exports: $Exports<'twilio/lib/TaskRouterTaskQueueCapability'>;
}
declare module 'twilio/lib/TaskRouterWorkerCapability.js' {
  declare module.exports: $Exports<'twilio/lib/TaskRouterWorkerCapability'>;
}
declare module 'twilio/lib/TaskRouterWorkspaceCapability.js' {
  declare module.exports: $Exports<'twilio/lib/TaskRouterWorkspaceCapability'>;
}
declare module 'twilio/lib/TrunkingClient.js' {
  declare module.exports: $Exports<'twilio/lib/TrunkingClient'>;
}
declare module 'twilio/lib/TwimlResponse.js' {
  declare module.exports: $Exports<'twilio/lib/TwimlResponse'>;
}
declare module 'twilio/lib/utils.js' {
  declare module.exports: $Exports<'twilio/lib/utils'>;
}
declare module 'twilio/lib/webhooks.js' {
  declare module.exports: $Exports<'twilio/lib/webhooks'>;
}
