const color = 'black'
export const idStyle = { width: '6vw', color };
export const nameStyle = { width: '14vw', textAlign: 'left', color };
export const phoneStyle = { width: '13vw', textAlign: 'left', color };
export const emailStyle = { width: '13 vw', textAlight: 'left', color};
export const nationalityStyle = { width: '11vw', textAlign: 'left', color };
export const flightCodeStyle = { width: '6vw', textAlign: 'left', color };
export const flightNumStyle = { width: '6vw', textAlign: 'left', color };
export const arrivalTimeStyle = {width: '15vw', textAlighn: 'left', color };
export const flightStatusStyle = {width: '8vw', textAlign: 'left', color };
export const travelerStatusStyle = {width: '8vw', textAlign: 'left', color };