export const SET_ALL_TRAVELERS = 'SET_ALL_TRAVELERS';
export const SET_SELECTED_TRAVELER = 'SET_SELECTED_TRAVELER';
export const UPDATE_TRAVELER = 'UPDATE_TRAVELER';
export const SET_FLIGHT = 'SET_FLIGHT';
export const SET_SIGNUP_TRAVELER = 'SET_SIGNUP_TRAVELER';
