export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';
export const SET_ALL_TRAVELERS = 'SET_ALL_TRAVELERS';
export const SET_SELECTED_TRAVELER = 'SET_SELECTED_TRAVELER';
export const UPDATE_TRAVELER = 'UPDATE_TRAVELER';
export const SET_FLIGHT = 'SET_FLIGHT';