name: Border Buddy CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: BorderBuddy_test
        ports:
          - 5432:5432 
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - name: Check out Repository Code
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm ci

    - name: Bootstrap Lerna
      run: npm run lerna:bootstrap
    
    - name: Run migrations 
      run: npm run migrate
     
    - name: Seed the database
      run: npm run seed

    - name: Build packages
      run: npm run build --if-present
    
    - name: Run all tests
      run: npm test

env:
  NODE_ENV: test
  SESSION_SECRET: ${{secrets.SESSION_SECRET}}
  TWILIO_ACCOUNT_SID: ${{secrets.TWILIO_ACCOUNT_SID}}
  TWILIO_AUTH_TOKEN: ${{secrets.TWILIO_AUTH_TOKEN}}
  TWILIO_MESSAGING_SID: ${{secrets.TWILIO_MESSAGING_SID}}
  TWILIO_PHONE_NUM: ${{secrets.TWILIO_PHONE_NUM}}
