name: Border Buddy CI

on:
  push:
    branches: [ ci-setup ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
    
    services:
      postgres:
        image: postgres
        env:
          # POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          # POSTGRES_DB: postgres
        ports:
          - 5432:5432 
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - name: Check out Repository Code
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm ci
    
    - name: Setup Postgres DB
      run: npm run build:test:db
      run: npm run migrate
      run: npm run seed
      env:
          NODE_ENV: test
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432

    - name: Build packages
      run: npm run build --if-present
    
    - name: Run mocha tests
      run: npm test
env:
  # DB_PASSWORD: postgres
  SESSION_SECRET: ${{secrets.SESSION_SECRET}}
  TWILIO_ACCOUNT_SID: ${{secrets.TWILIO_ACCOUNT_SID}}
  TWILIO_AUTH_TOKEN: ${{secrets.TWILIO_AUTH_TOKEN}}
  TWILIO_MESSAGING_SID: ${{secrets.TWILIO_MESSAGING_SID}}
  TWILIO_PHONE_NUM: ${{secrets.TWILIO_PHONE_NUM}}
