# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
env:
  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
  SESSION_SECRET: ${{secrets.SESSION_SECRET}}
  TWILIO_ACCOUNT_SID: ${{secrets.TWILIO_ACCOUNT_SID}}
  TWILIO_AUTH_TOKEN: ${{secrets.TWILIO_AUTH_TOKEN}}
  TWILIO_MESSAGING_SID: ${{secrets.TWILIO_MESSAGING_SID}}
  TWILIO_PHONE_NUM: ${{secrets.TWILIO_PHONE_NUM}}
